// pages/api/pdf/generate.js
// ─────────────────────────────────────────────────────────────────
// Generates a real PDF file server-side using Puppeteer.
// Returns a PDF buffer for download.
// 
// Install: npm install puppeteer-core @sparticuz/chromium
// ─────────────────────────────────────────────────────────────────

import chromium from "@sparticuz/chromium";
import puppeteer from "puppeteer-core";
import { getAuth } from "@clerk/nextjs/server";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

function buildDocumentHTML(result, meta) {
  const { caseTitle, claimType, jurisdiction, date, caseNum } = meta;
  const scoreColor = result.claimScore >= 8 ? "#10B981" : result.claimScore >= 6 ? "#F59E0B" : "#EF4444";

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Times New Roman', Georgia, serif; font-size: 14px; line-height: 1.75; color: #0A0A0A; background: #fff; padding: 60px; }
  .header { text-align: center; padding-bottom: 28px; border-bottom: 1px solid #ccc; margin-bottom: 28px; }
  .header .label { font-size: 11px; letter-spacing: .14em; text-transform: uppercase; color: #555; margin-bottom: 8px; font-family: Arial, sans-serif; }
  .header h1 { font-size: 26px; font-weight: 700; margin-bottom: 6px; }
  .header .meta { font-size: 12px; color: #555; }
  .section-title { font-size: 12px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; border-bottom: 1.5px solid #0A0A0A; padding-bottom: 5px; margin-bottom: 14px; margin-top: 28px; font-family: Arial, sans-serif; }
  .score-box { text-align: center; padding: 20px; border: 1px solid #ddd; border-radius: 8px; margin: 16px 0; }
  .score-value { font-size: 36px; font-weight: 700; color: ${scoreColor}; }
  .score-label { font-size: 13px; color: ${scoreColor}; font-family: Arial, sans-serif; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
  th { text-align: left; padding: 7px 10px; border-bottom: 1px solid #ccc; font-size: 12px; font-weight: 700; letter-spacing: .04em; font-family: Arial, sans-serif; }
  td { padding: 7px 10px; border-bottom: 1px solid #eee; font-size: 13px; }
  td.amount { font-weight: 600; }
  .item { padding-left: 20px; margin-bottom: 7px; }
  .disclaimer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ccc; font-size: 11px; color: #777; line-height: 1.65; font-family: Arial, sans-serif; }
  .footer { display: flex; justify-content: space-between; margin-top: 24px; padding-top: 12px; border-top: 1px solid #eee; font-size: 11px; color: #aaa; font-family: Arial, sans-serif; }
  p { margin-bottom: 8px; }
</style>
</head>
<body>
  <div class="header">
    <div class="label">Legal Analysis Report &middot; Confidential</div>
    <h1>ClaimSmart AI Platform</h1>
    <div class="meta">Case No. ${caseNum} &middot; ${date} &middot; ${jurisdiction || "N/A"}</div>
    <div class="meta" style="margin-top:4px;font-size:11px;color:#888;">Generated by artificial intelligence. For informational purposes only.</div>
  </div>

  <div class="section-title">1. Executive Summary</div>
  <p><strong>Claim Category:</strong> ${(claimType || "").replace(/_/g, " ")}</p>
  <p><strong>Claim Strength Rating:</strong> ${result.claimScore}/10</p>
  <p><strong>Recommended Compensation:</strong> ${result.estimatedRecommended}</p>
  <div class="score-box">
    <div class="score-value">${result.claimScore}/10</div>
    <div class="score-label">${result.claimScore >= 8 ? "Strong Claim" : result.claimScore >= 6 ? "Moderate Claim" : "Needs Work"}</div>
  </div>
  <p>${result.verdict}</p>

  <div class="section-title">2. Case Strengths</div>
  ${(result.strengths || []).map((s, i) => `<p class="item">(${i+1}) ${s}</p>`).join("")}

  <div class="section-title">3. Risk Factors and Weaknesses</div>
  ${(result.weaknesses || []).map((w, i) => `<p class="item">(${i+1}) ${w}</p>`).join("")}

  ${result.missingEvidence?.length ? `
  <div class="section-title">4. Missing Evidence</div>
  ${result.missingEvidence.map((m, i) => `<p class="item">(${i+1}) ${m}</p>`).join("")}
  ` : ""}

  <div class="section-title">5. Compensation Analysis</div>
  <table>
    <thead><tr><th>Scenario</th><th>Estimated Amount</th></tr></thead>
    <tbody>
      <tr><td>Minimum</td><td class="amount">${result.estimatedMin}</td></tr>
      <tr><td>Recommended</td><td class="amount" style="color:#2563EB;">${result.estimatedRecommended}</td></tr>
      <tr><td>Maximum</td><td class="amount">${result.estimatedMax}</td></tr>
    </tbody>
  </table>

  <div class="section-title">6. Legal Strategy</div>
  <p>${result.legalStrategy}</p>

  <div class="section-title">7. Recommended Next Steps</div>
  ${(result.nextSteps || []).map((s, i) => `<p class="item">(${i+1}) ${s}</p>`).join("")}

  <div class="disclaimer">
    <strong style="color:#333;">Important Disclaimer:</strong> This report was generated by ClaimSmart AI 
    for informational purposes only. It does not constitute legal advice and should not be relied upon 
    as a substitute for professional legal counsel. The accuracy of this analysis depends on the 
    information provided. Please consult a licensed attorney before taking legal action.
  </div>

  <div class="footer">
    <span>ClaimSmart AI &middot; ${date}</span>
    <span>Case ${caseNum} &middot; Page 1 of 1</span>
  </div>
</body>
</html>`;
}

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).end();

  const { userId } = getAuth(req);
  if (!userId) return res.status(401).json({ error: "Unauthorized" });

  const { result, caseTitle, claimType, jurisdiction, caseId } = req.body;
  if (!result) return res.status(400).json({ error: "result required" });

  const date = new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" });
  const caseNum = "CS-" + String(Date.now()).slice(-6);

  const html = buildDocumentHTML(result, { caseTitle, claimType, jurisdiction, date, caseNum });

  let browser;
  try {
    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top:"0", bottom:"0", left:"0", right:"0" },
    });

    // Optionally save to Supabase Storage
    if (caseId) {
      const path = userId + "/" + caseId + "/report.pdf";
      await supabase.storage.from("pdf-exports").upload(path, pdfBuffer, {
        contentType: "application/pdf",
        upsert: true,
      });
    }

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=claimsmart-report-" + caseNum + ".pdf");
    return res.send(pdfBuffer);
  } catch (err) {
    console.error("PDF generation error:", err);
    return res.status(500).json({ error: "PDF generation failed. Please try again." });
  } finally {
    if (browser) await browser.close();
  }
}

export const config = {
  api: { bodyParser: { sizeLimit: "2mb" }, responseLimit: "10mb" },
};
